#cloud-config
runcmd:
  # wait for docker + network
  - sleep 15

  # download model if not already present
  - |
    if [ ! -f /opt/dlami/nvme/large-v3.pt ]; then
      echo "Downloading model from S3..."
      aws s3 cp s3://portal-daf-yomi-models/whisper-large-v3.pt /opt/dlami/nvme/large-v3.pt --no-progress
    else
      echo "Model already exists, skipping download."
    fi

  # download and load docker image from S3
  - aws s3 cp s3://portal-docker-images/whisper-timestamp.tar.gz - | docker load

  # create CloudWatch Agent config
  - |
    mkdir -p /opt/aws/amazon-cloudwatch-agent/etc

    cat >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<'EOF'
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/lib/docker/containers/*/*-json.log",
                "log_group_name": "/docker/whisper-timestamp",
                "log_stream_name": "{instance_id}",
                "timestamp_format": "%Y-%m-%dT%H:%M:%S"
              }
            ]
          }
        }
      }
    }
    EOF

  # start CloudWatch Agent
  - |
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
      -a fetch-config \
      -m ec2 \
      -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
      -s

  # run container
  - docker run -d --gpus all --restart unless-stopped -v /opt/dlami/nvme:/opt/dlami/nvme whisper-timestamp:1
